name: Auto-close PRs

on:
  pull_request:
    types: [opened]

jobs:
  close_pr:
    if: github.actor != 'L-Gardiner'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: peter-evans/close-pull-request@v3
        with:
          comment: |
            🚫 This repository does not accept external contributions.
            Your pull request has been closed automatically.
